<a href="https://colab.research.google.com/github/Akbhartiq/NumpyTuts/blob/master/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Welcome to the World of Machine Learning
# Day 1
import numpy as np
print(np.__version__)

1.25.2


In [ ]:
list1=["Aditya Kumar Bharti",20,"IIT Kharagpur"]
print(list1)
# Working with list when size of data is much more , the computation becomes pretty slow

['Aditya Kumar Bharti', 20, 'IIT Kharagpur']


In [ ]:
# Get ready with numpy(Numeric Python: Same Data-Type)
# Data-type of numpy array is ndarray (n-dimensional array)

# 1st way to create numpy array
np1=np.array([0,1,2,3,4,5])
print(np1)
print(type(np1))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# To get the shape of numpy array
print(np1.shape)

(6,)


In [ ]:
# To use the range function to create numpy array
np2=np.arange(10)
print(np2)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Better version
start=1
end=19
step=3
np3=np.arange(start,end,step)
print(np3)
print(np3.shape)

[ 1  4  7 10 13 16]
(6,)


In [ ]:
# Zero array (often use to init a numpy array)
np4=np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Multidimensional Zeros
np5=np.zeros((3,4))
print(np5)
print(np5.shape)


# Get the type of np.shape
print(type(np5.shape)) #:: It is a tuple

# To get the number of Elements
def numOfElem(z):
  numOfDim=np.ndim(z)
  val=1
  for i in range(numOfDim):
    val*=z.shape[i]
  return val


print(f"Number of Elements in np5 is {numOfElem(np5)}")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
<class 'tuple'>
Number of Elements in np5 is 12


In [ ]:
# Full function
np6=np.full((10,3),6)
print(np6)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
# Converting python list to numpy array
list2=[1,2,3]

np7=np.array(list2)
print(np7)
print(type(np7))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# Accessing elements

# Understand the np.len function
length=len(np7)
print(length)

# what about multi-dimensional array
np8=np.full((2,3),4)
length=len(np8) #Length gives you the number of elements across 0th-axis
print(length)

# Accessing  Elements
print(np8[0,1])
print(np7[1])

3
2
4
2


In [ ]:
# Welcome to the Day-2 of numpy array Tutorials

'''We'll learn about slicing numpy arrays'''

# Slcing numpy arrays
np1=np.array([1,2,3,4,5,6,7,8,9])
print(np1[1:5]) # Basic Idea is that np[start:end:step]



[2 3 4 5]


In [ ]:
# Reverse the np array based on the concept of the Slicing
np2=np1[::-1]   # Negative step expect start to be higher than end
print(np2)

# 2nd Example
np3=np1[0:3:-1]
print(np3)

[9 8 7 6 5 4 3 2 1]
[]


In [ ]:
# Slicing a 2D array
np4=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

# To print 8
print(np4[1][3])
print(np4[1,3])

# To get the 2D matrix 2,3,6,7
print(np4[0:2,1:3])
print(np4[0:2][1:3])


# To get 1D matrix 4,8,12
print(np4[:,3:]) # Notice that it is still a 2D matrix
print((np4[:,3:]).shape)


# To get 1D matrix
print((np4[1]).shape) #This is 1D matrix


8
8
[[2 3]
 [6 7]]
[[5 6 7 8]]
[[ 4]
 [ 8]
 [12]]
[]
(3, 1)
(4,)


In [ ]:
# Welcome to the Day-3
# Universal Functions in Numpy
'''The Functions that we will be learning over here will be something like which will be kind of iterate
over each Element in the numpy array and do some operation to that element and return a new numpy array'''

# Finding square root of each element in the array
import numpy as np
np1=np.array([1,-2,3,4])
np2=np.sqrt(np1)
print(np2)

# Finding the e raised to element
np3=np.exp(np1)
print(np3)



[1.                nan 1.73205081 2.        ]
[ 2.71828183  0.13533528 20.08553692 54.59815003]


<ipython-input-4-84f74555b76e>:9: RuntimeWarning: invalid value encountered in sqrt
  np2=np.sqrt(np1)


In [ ]:
# To get the absolute value
np4=np.absolute(np1)
print(np4)

[1 2 3 4]


In [ ]:
# Functions with one ret value

# Min/max
minimum=np.min(np1)
maximum=np.max(np1)

print(f"Minimum Value is {minimum}")
print(f"Maximum Value is {maximum}")


# Index Corresponding to min/max value
min_index=np.argmin(np1)
max_index=np.argmax(np1)

print(f"Index Corresponding to min value is {min_index}")
print(f"Index Corresponding to max value is {max_index}")


# To get the sum of all Elements
sum=np.sum(np1)
print(f"Sum of all Elements is {sum}")

Minimum Value is -2
Maximum Value is 4
Index Corresponding to min value is 1
Index Corresponding to max value is 3
Sum of all Elements is 6


In [ ]:
# To get the sign of all Elements
'''-1 for Negative
    0 for Zeros
    1 for positive
    Values   '''

sign_arr=np.sign(np1)
print(sign_arr)

[ 1 -1  1  1]


In [ ]:
# Trigo functions
np1=np.array([1.577,3.14])
print(np.sin(np1))
print(np.cos(np1))
print(np.tan(np1))

[0.99998076 0.00159265]
[-0.00620363 -0.99999873]
[-1.61192754e+02 -1.59265494e-03]


In [ ]:
# To calculat log
np1=np.array([10,1])
np2=np.array([2.73,1])
print(np.log(np1))
print(np.log(np2))

[2.30258509 0.        ]
[1.00430161 0.        ]


**Ref-to-doc:**https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs


In [ ]:
# Welcome to the Day-4
# Copy vs View
'''Copy: simply copy of the Original Array
   View: It is connected to the Original Array'''


import numpy as np
np1=np.array([1,2,3,4,5])

# Create a view
np2=np1.view()

print(f"Original np1: {np1}")
print(f"Original np2: {np2}")

np1[0]=10

print(f"Changed np1: {np1}")
print(f"Original np2: {np2}")

Original np1: [1 2 3 4 5]
Original np2: [1 2 3 4 5]
Changed np1: [10  2  3  4  5]
Original np2: [10  2  3  4  5]


In [ ]:
# Create a copy
np1[0]=1

np3=np1.copy()

print(f"Original np1: {np1}")
print(f"Original np3: {np3}")

np1[0]=10

print(f"Changed np1: {np1}")
print(f"Original np3: {np3}")

Original np1: [1 2 3 4 5]
Original np3: [1 2 3 4 5]
Changed np1: [10  2  3  4  5]
Original np3: [1 2 3 4 5]


In [ ]:
# Let's try to change the view and see its effects on original array
np2[0]=100

print(f"Changed np2: {np2}")
print(f"Original np1: {np1}")

Changed np2: [100   2   3   4   5]
Original np1: [100   2   3   4   5]


In [ ]:
# Welcome to the Day-5
'''Today we will learn about the shape and the reshape'''

import numpy as np

# Create 1D array and get its shape
np1=np.arange(10)
print(np1.shape)

(10,)


In [ ]:
# Create 2D array and get its shape
np2=np.random.randint(10,21,size=(3,4))
print(np2)
print(np2.shape)

[[12 13 13 20]
 [11 17 18 16]
 [17 12 14 17]]
(3, 4)


In [ ]:
# Reshape into 2D array
np3=np1.reshape(2,5)
print(np3)
print(np3.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [ ]:
# Reshape into 3D array
np4=np2.reshape(2,2,3)
print(np4)
print(np4.shape)

[[[12 13 13]
  [20 11 17]]

 [[18 16 17]
  [12 14 17]]]
(2, 2, 3)


In [ ]:
# Flatten to 1D
np5=np4.reshape(-1) #-1: only one param so 1-dimensional now get the number of elements that will be dimension
print(np5)
print(np5.shape)

[12 13 13 20 11 17 18 16 17 12 14 17]
(12,)


In [ ]:
# Flatten to 2D
np6=np4.reshape(-1,3) # Here we got 2Dimesions with 3 cols and value of -1 =4
print(np6)
print(np6.shape)

[[12 13 13]
 [20 11 17]
 [18 16 17]
 [12 14 17]]
(4, 3)


In [ ]:
# Welcome to the Day-6
'''Iteration through the Elements in Numpy array'''

# Basic one(Don't work for multi-Dimensional array)
def iterate1(z):
  for val in z:
    print(val)


# Bit tougher to write-as you don't know how many for-loop to be added
def iterate2(z):
  ndim=np.ndim(z)
  shape=z.shape
  for i in range(shape[0]):
    pass

# Can we write a Recursive one
def iterate3(z):
  ndim=np.ndim(z)
  shape=z.shape
  if ndim==1:
    for val in z:
      print(val)
  else:
    for val in z:
      iterate3(val)


import numpy as np
np1=np.random.randint(10,21,size=(3,4))
print("Iteration1 Begin")
iterate1(np1)
print("Iteration1 End")

print("Iteration3 Begin")
iterate3(np1)
print("Iteration3 End")

Iteration1 Begin
[17 18 20 10]
[11 19 11 12]
[18 14 20 20]
Iteration1 End
Iteration3 Begin
17
18
20
10
11
19
11
12
18
14
20
20
Iteration3 End


In [ ]:
# using numpy iterator to do so
def iterate4(z):
  for x in np.nditer(z):
    print(x)

iterate4(np1)

17
18
20
10
11
19
11
12
18
14
20
20


In [ ]:
# Welcome to the Day-7
'''Sorting Numpy arrays'''
import numpy as np
np1=np.array([3,2,9,4,2,-1])
np2=np.sort(np1)

print(np1)
print(np2)

[ 3  2  9  4  2 -1]
[-1  2  2  3  4  9]


In [ ]:
# Sorting 2D array (Sort each particular row, sort along last axis)
np3=np.random.randint(10,21,size=(3,4))

print(np.sort(np3))

[[13 17 17 19]
 [10 11 12 15]
 [13 15 17 20]]


In [ ]:
# Similar Things we can do with Names
np4=np.array(["Aditya","John","Ashish","Harry"])
print(np.sort(np4))

['Aditya' 'Ashish' 'Harry' 'John']


In [ ]:
# Bool
np5=np.array([True,False,True,False])
print(np5)
print(np.sort(np5))

[ True False  True False]
[False False  True  True]


In [ ]:
# Note: Sorting doesn't change the original
print(np5)

[ True False  True False]


In [ ]:
# Welcome to the Day-08
'''Searching Elements in numpy array'''

import numpy as np

#Search
np1=np.array([1,2,3,4,5,3,7,8,9])

x=np.where(np1==3) #Iterate over array and returs indices where Element is 3
print(x[0])
print(len(x))
print(type(x))
print(np1[x[0]])

[2 5]
1
<class 'tuple'>
[3 3]


In [ ]:
# Searching in 2D arrays
np2=np.array([
    [1,3,1],
    [2,3,1]
])

x=np.where(np2==3)
print(x)
print(len(x))
print(type(x))


# So you wanna get the Exact index
print(f"Index of 3 in np2 is {x[0][0]},{x[1][0]}")

(array([0, 1]), array([1, 1]))
2
<class 'tuple'>
Index of 3 in np2 is 0,1


In [ ]:
# Get the pos of Even numbers
x=np.where(np1 %2==0)
print(x)

(array([1, 3, 7]),)


In [ ]:
# Get the pos of Odd Numbers
x=np.where(np1 %2==1)
print(x)

(array([0, 2, 4, 5, 6, 8]),)


In [ ]:
# Welcome to the Day-09
'''Filterring Numpy arrays'''
import numpy as np
np1=np.array([1,2,3,4,5,6,7,8,9,10])
x1=[True,False,True,False,True,False,True,False,True,True] #True:Get , False:don't get
x2=[1,0,1,0,1,0,1,0,1,1] #This won't work
print(np1[x1])
print(np1[x2])

[ 1  3  5  7  9 10]
[2 1 2 1 2 1 2 1 2 2]


In [ ]:
# Filterring even numbers
x=np1%2==0
print(x)

[False  True False  True False  True False  True False  True]
